version: "3.7"
services:
    app:
        build:
            args:
                user: MuhammadMahediHasan
                uid: 1000
            context: ./
            dockerfile: Dockerfile
        image: address-platform
        container_name: laravel-job-portal-backend
        restart: unless-stopped
        working_dir: /var/www/
        volumes:
            - ./:/var/www
        depends_on:
            - database
        links:
            - database
        networks:
            - laravel-job-portal-backend-network
    nginx:
        image: nginx:alpine
        container_name: laravel-job-portal-nginx
        restart: unless-stopped
        ports:
            - "${NGINX_PORT}:80"
        volumes:
            - ./:/var/www
            - ./.docker/nginx:/etc/nginx/conf.d/
        networks:
            - laravel-job-portal-backend-network
        depends_on:
            - database
            - phpmyadmin
    database:
        image: mariadb
        container_name: laravel-job-portal-backend-database
        restart: unless-stopped
        environment:
            MYSQL_DATABASE: ${DB_DATABASE}
            MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
            MYSQL_PASSWORD: ${DB_PASSWORD}
            MYSQL_USER: ${DB_USERNAME}
            SERVICE_TAGS: dev
            SERVICE_NAME: mysql
        networks:
            - laravel-job-portal-backend-network
    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        container_name: laravel-job-portal-backend-phpmyadmin
        restart: unless-stopped
        tty: true
        depends_on:
            - database
        ports:
            - "${PMA_PORT}:80"
        environment:
            PMA_HOST: database
            PMA_PORT: 3306
            PMA_USER: ${DB_USERNAME}
            PMA_PASSWORD: ${DB_PASSWORD}
            MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
            UPLOAD_LIMIT: 2048M
        networks:
            - laravel-job-portal-backend-network
networks:
    laravel-job-portal-backend-network:
        driver: bridge
